# Number of execution units
alu = 32
compare = 32
agu = 32
load = 32
multiply = 32

fetchDecodeWidth = 16
commitWidth = 16

# Buffer Sizes
aluRs = 32
multiplyRs = 32
compareRs = 32
aguRs = 32
aguLoadBuffer = 32
fetchDecodeBuffer = 16
decodeIssueBuffer = 16
issueBranchBuffer = 16
rob = 128
