# Number of execution units
alu = 8
compare = 4
agu = 4
load = 4
multiply = 8

fetchDecodeWidth = 8
commitWidth = 8

# Buffer Sizes
aluRs = 32
multiplyRs = 32
compareRs = 32
aguRs = 32
aguLoadBuffer = 32
fetchDecodeBuffer = 16
decodeIssueBuffer = 16
issueBranchBuffer = 2
rob = 128
